name: ✨ Propuesta de mejora
description: Sugiere una nueva funcionalidad o mejora
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: ¿Qué problema resuelve?
      description: Explica la necesidad detrás de la propuesta.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solución propuesta
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas consideradas
    validations:
      required: false
